# Generated by Django 5.2.3 on 2025-07-24 07:38

import django.db.models.deletion
import itinerary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='itineraryday',
            new_name='itineraryDay',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborating_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('flight', 'Flight'), ('insurance', 'Insurance')], max_length=20)),
                ('file', models.FileField(upload_to=itinerary.models.document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.itinerary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
