# Generated by Django 5.2.3 on 2025-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_activity_created_at_activity_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='itineraryDay',
            new_name='itinerary_day',
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
