# Generated by Django 5.2.3 on 2025-07-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_rename_itineraryday_activity_itinerary_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='collaborators',
        ),
    ]
