# Generated by Django 5.2.3 on 2025-08-02 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_remove_itinerary_collaborators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('itinerary', 'user', 'doc_type')},
        ),
    ]
