# Generated by Django 5.2.3 on 2025-07-10 08:42

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.svg', null=True, upload_to=user.models.user_avatar_path),
        ),
    ]
